/**
 * generated by Xtext
 */
package hu.elte.refjava.lang.tests;

import hu.elte.refjava.lang.tests.RefJavaInjectorProvider;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(RefJavaInjectorProvider.class)
@SuppressWarnings("all")
public class RefJavaParsingTest {
}
