/*
 * generated by Xtext
 */
package hu.elte.refjava.lang.tests

import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.junit.jupiter.api.^extension.ExtendWith

@ExtendWith(InjectionExtension)
@InjectWith(RefJavaInjectorProvider)
class RefJavaParsingTest {
	
}
