/*
 * generated by Xtext
 */
package hu.elte.refjava.lang.ui.tests;

import com.google.inject.Injector;
import hu.elte.refjava.lang.ui.internal.LangActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class RefJavaUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LangActivator.getInstance().getInjector("hu.elte.refjava.lang.RefJava");
	}

}
